### ISSUE TITLE
Download the table with css style.

### ISSUE THREAD

**Issue by Junjie2412** [zsusac/ReactHTMLTableToExcel#11]
My react tables have some cells with background color.  Is there some way to download the table in such a way that it retains the background color of the cells?

Thank you.

**Comment by Junjie2412** [comment]
Sorry fixed this.  used style instead of classname

**Comment by puzant** [comment]
having the same issue used style & className but neither is working

**Comment by shankar343** [comment]
Use Inline style for the table cells having different color.
Ex- <td style={{backgroundColor : color}}>CELL</td>
